name = "Wordlegames"
uuid = "1cb69566-e1cf-455f-a587-fd79a2e00f5a"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
ThreadsX = "0.1"
julia = "1.7"

[extras]
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Primes", "Tables"]
