name = "Wordlegames"
uuid = "1cb69566-e1cf-455f-a587-fd79a2e00f5a"
authors = ["Douglas Bates <dmbates@gmail.com> and contributors"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ThreadsX = "ac1d9e8a-700a-412c-b207-f0111f4b6c0d"

[compat]
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
